/**
 * Social layer error codes and types
 */

/**
 * Social-specific error codes
 */
export const SOCIAL_ERROR_CODES = {
  // Social layer errors
  SOCIAL_ERROR: 'SOCIAL_ERROR',
  LIST_NOT_FOUND: 'LIST_NOT_FOUND',
  LIST_EXISTS: 'LIST_EXISTS',
  INVALID_LIST_NAME: 'INVALID_LIST_NAME',
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  REPOSITORY_NOT_FOUND: 'REPOSITORY_NOT_FOUND',
  ALREADY_FOLLOWING: 'ALREADY_FOLLOWING',
  NOT_FOLLOWING: 'NOT_FOLLOWING',
  MISSING_CONTENT: 'MISSING_CONTENT',
  INTERACTION_ERROR: 'INTERACTION_ERROR',
  SEARCH_ERROR: 'SEARCH_ERROR',
  CONFIG_ERROR: 'CONFIG_ERROR',

  // Generic operation errors
  CREATE_ERROR: 'CREATE_ERROR',
  DELETE_ERROR: 'DELETE_ERROR',
  UPDATE_ERROR: 'UPDATE_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PERMISSION_ERROR: 'PERMISSION_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR'
} as const;

export type SocialErrorCode = typeof SOCIAL_ERROR_CODES[keyof typeof SOCIAL_ERROR_CODES];
