name: Mirror

on:
  push:
    branches: [main, "gitmsg/**"]
    tags: ["v*"]
  workflow_dispatch:

jobs:
  gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_PAT }}@gitlab.com/gitsocial-org/gitsocial.git
          git fetch origin 'refs/gitmsg/*:refs/gitmsg/*'
          git push gitlab --all --force
          git push gitlab --tags --force
          git lfs push gitlab --all || true
          git push gitlab 'refs/gitmsg/*:refs/gitmsg/*' --force

  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git remote add codeberg https://${{ secrets.CODEBERG_PAT }}@codeberg.org/GitSocial/gitsocial.git
          git fetch origin 'refs/gitmsg/*:refs/gitmsg/*'
          git push codeberg --all --force
          git push codeberg --tags --force
          git lfs push codeberg --all || true
          git push codeberg 'refs/gitmsg/*:refs/gitmsg/*' --force
